# Generated by Django 5.0.14 on 2025-09-27 17:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "expenses",
            "0006_expense_payment_source_alter_expense_payment_method_and_more",
        ),
        ("users", "0003_userprofile_ui_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Importo contributo",
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importo ancora disponibile per le spese",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Saldo disponibile",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descrizione"),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("contanti", "Contanti"),
                            ("bonifico", "Bonifico Ricevuto"),
                            ("stipendio", "Stipendio"),
                            ("regalo", "Regalo"),
                            ("rimborso", "Rimborso"),
                            ("vendita", "Vendita"),
                            ("altro", "Altro"),
                        ],
                        default="contanti",
                        max_length=20,
                        verbose_name="Tipo di contributo",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data contributo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Note aggiuntive")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponibile", "Disponibile"),
                            ("parzialmente_utilizzato", "Parzialmente Utilizzato"),
                            ("esaurito", "Esaurito"),
                        ],
                        default="disponibile",
                        max_length=30,
                        verbose_name="Stato",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="users.family",
                        verbose_name="Famiglia",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utente che ha contribuito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contributo",
                "verbose_name_plural": "Contributi",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_used",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Importo utilizzato",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_contributions",
                        to="contributions.contribution",
                        verbose_name="Contributo",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_contributions",
                        to="expenses.expense",
                        verbose_name="Spesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilizzo Contributo",
                "verbose_name_plural": "Utilizzi Contributi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_contributions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Totale contributi",
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Totale spese da contributi",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo attuale",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultimo aggiornamento"
                    ),
                ),
                (
                    "family",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="users.family",
                        verbose_name="Famiglia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saldo Famiglia",
                "verbose_name_plural": "Saldi Famiglie",
            },
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(fields=["-date"], name="contributio_date_b0b45d_idx"),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["user", "-date"], name="contributio_user_id_51c330_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(fields=["status"], name="contributio_status_f01602_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="expensecontribution",
            unique_together={("expense", "contribution")},
        ),
    ]
