# Generated by Django 5.1.7 on 2025-09-16 22:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('type', models.CharField(choices=[('necessaria', 'Necessaria'), ('extra', 'Extra')], default='necessaria', max_length=20, verbose_name='Tipo di spesa')),
                ('icon', models.CharField(blank=True, help_text="Nome dell'icona da visualizzare", max_length=50, verbose_name='Icona')),
                ('color', models.CharField(blank=True, help_text='Colore in formato HEX (es. #FF5733)', max_length=7, verbose_name='Colore')),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget mensile')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome sottocategoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Sottocategoria',
                'verbose_name_plural': 'Sottocategorie',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
