# Generated by Django 5.0.14 on 2025-09-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text="Lista di alias per la ricerca (es. ['benzina', 'gasolio'] per 'carburante')", verbose_name='Alias'),
        ),
    ]
