# Generated by Django 5.0.14 on 2025-09-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_subcategory_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Nome dell'icona Material Design da visualizzare", max_length=50, verbose_name='Icona'),
        ),
    ]
