# Generated by Django 5.1.7 on 2025-09-17 00:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='es. 1.0.0', max_length=20)),
                ('version_code', models.IntegerField(help_text='Numero versione incrementale', unique=True)),
                ('apk_file', models.FileField(help_text='File APK', upload_to='apk/')),
                ('release_notes', models.TextField(blank=True, help_text='Note di rilascio')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Aggiornamento obbligatorio')),
                ('min_supported_version', models.IntegerField(help_text='Versione minima supportata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Versione App',
                'verbose_name_plural': 'Versioni App',
                'ordering': ['-version_code'],
            },
        ),
    ]
