# Generated by Django 5.0.14 on 2025-09-18 00:46

import apps.updates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='apk_file',
            field=models.FileField(help_text='File APK', upload_to=apps.updates.models.apk_upload_path),
        ),
    ]
