# Generated by Django 5.1.7 on 2025-09-17 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Famiglia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invite_code', models.CharField(max_length=8, unique=True, verbose_name='Codice Invito')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_families', to=settings.AUTH_USER_MODEL, verbose_name='Creata da')),
            ],
            options={
                'verbose_name': 'Famiglia',
                'verbose_name_plural': 'Famiglie',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.family', verbose_name='Famiglia'),
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Invitato')),
                ('family_role', models.CharField(choices=[('master', 'Master (Genitore)'), ('familiare', 'Familiare')], default='familiare', max_length=20, verbose_name='Ruolo Proposto')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token Invito')),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('accepted', 'Accettato'), ('declined', 'Rifiutato'), ('expired', 'Scaduto')], default='pending', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Scade il')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.family', verbose_name='Famiglia')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitato da')),
            ],
            options={
                'verbose_name': 'Invito Famiglia',
                'verbose_name_plural': 'Inviti Famiglia',
                'unique_together': {('family', 'email', 'status')},
            },
        ),
    ]
