# Generated by Django 5.0.14 on 2025-09-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_family_user_family_familyinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ui_preferences',
            field=models.JSONField(blank=True, default=dict, help_text="Impostazioni personalizzate dell'interfaccia (font, colori, etc.)", verbose_name='Preferenze UI'),
        ),
    ]
