# Generated by Django 5.1.7 on 2025-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Dati personali sensibili crittografati (email, nome, telefono, etc.)', verbose_name='Profilo Crittografato'),
        ),
        migrations.AddField(
            model_name='user',
            name='encryption_version',
            field=models.IntegerField(default=1, help_text="Versione dell'algoritmo di crittografia utilizzato", verbose_name='Versione Crittografia'),
        ),
    ]
