# Generated by Django 5.1.7 on 2025-09-16 22:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome budget')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('year', models.IntegerField(verbose_name='Anno')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mese')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo totale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budget',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Categoria',
                'verbose_name_plural': 'Budget Categorie',
            },
        ),
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome obiettivo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo obiettivo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Importo attuale')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Data obiettivo')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obiettivo di Risparmio',
                'verbose_name_plural': 'Obiettivi di Risparmio',
                'ordering': ['-created_at'],
            },
        ),
    ]
