# Generated by Django 5.1.7 on 2025-09-16 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='users',
            field=models.ManyToManyField(related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='Utenti'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='reports.budget', verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='users',
            field=models.ManyToManyField(related_name='saving_goals', to=settings.AUTH_USER_MODEL, verbose_name='Utenti'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('year', 'month', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('budget', 'category')},
        ),
    ]
