# Generated by Django 5.1.7 on 2025-09-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budget'},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(choices=[('monthly', 'Mensile'), ('seasonal', 'Stagionale'), ('event', 'Evento/Occasione'), ('yearly', 'Annuale'), ('custom', 'Personalizzato')], default='custom', max_length=20, verbose_name='Tipo budget'),
        ),
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default='2025-09-30', verbose_name='Data fine'),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default='2025-09-01', verbose_name='Data inizio'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
    ]
