# Generated by Django 5.1.7 on 2025-09-17 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('expenses', '0002_initial'),
        ('reports', '0003_update_budget_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome piano spese')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('plan_type', models.CharField(choices=[('monthly', 'Mensile'), ('seasonal', 'Stagionale'), ('event', 'Evento/Occasione'), ('yearly', 'Annuale'), ('custom', 'Personalizzato')], default='custom', max_length=20, verbose_name='Tipo piano')),
                ('start_date', models.DateField(default='2025-09-01', verbose_name='Data inizio')),
                ('end_date', models.DateField(default='2025-09-30', verbose_name='Data fine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='spending_plans', to=settings.AUTH_USER_MODEL, verbose_name='Utenti')),
            ],
            options={
                'verbose_name': 'Piano Spese',
                'verbose_name_plural': 'Piani Spese',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrizione spesa')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importo stimato per questa spesa', max_digits=10, verbose_name='Importo stimato')),
                ('priority', models.CharField(choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorità')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data scadenza')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_expense', models.ForeignKey(blank=True, help_text='Spesa effettiva collegata a questa pianificazione', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expense', verbose_name='Spesa reale')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Categoria')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory', verbose_name='Sottocategoria')),
                ('spending_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_expenses', to='reports.spendingplan', verbose_name='Piano spese')),
            ],
            options={
                'verbose_name': 'Spesa Pianificata',
                'verbose_name_plural': 'Spese Pianificate',
                'ordering': ['due_date', '-priority', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='reports.spendingplan', verbose_name='Budget'),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
