# Generated by Django 5.0.14 on 2025-09-17 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_create_spending_plan_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_spending_plans', to=settings.AUTH_USER_MODEL, verbose_name='Creato da'),
        ),
        migrations.AddField(
            model_name='spendingplan',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='Se False, il piano è visibile solo al creatore', verbose_name='Condiviso con famiglia'),
        ),
    ]
