# Generated by Django 5.0.14 on 2025-09-17 22:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_spendingplan_created_by_spendingplan_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingplan',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budget complessivo pianificato per questo periodo', max_digits=10, verbose_name='Budget totale pianificato'),
        ),
    ]
