# Generated by Django 5.0.14 on 2025-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_spendingplan_total_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedexpense',
            name='installment_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Numero rata corrente'),
        ),
        migrations.AddField(
            model_name='plannedexpense',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Spesa ricorrente'),
        ),
        migrations.AddField(
            model_name='plannedexpense',
            name='parent_recurring_id',
            field=models.CharField(blank=True, help_text='Identifica il gruppo di rate collegate', max_length=50, null=True, verbose_name='ID gruppo ricorrenza'),
        ),
        migrations.AddField(
            model_name='plannedexpense',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensile'), ('bimonthly', 'Bimestrale')], default='monthly', max_length=20, null=True, verbose_name='Frequenza ricorrenza'),
        ),
        migrations.AddField(
            model_name='plannedexpense',
            name='total_installments',
            field=models.PositiveIntegerField(blank=True, help_text='Es: 10 per dentista in 10 rate', null=True, verbose_name='Numero rate totali'),
        ),
        migrations.AddField(
            model_name='spendingplan',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Indica se il piano è stato creato automaticamente da ricorrenze', verbose_name='Generato automaticamente'),
        ),
        migrations.AddField(
            model_name='spendingplan',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Se True, il piano non viene mostrato nelle liste principali', verbose_name='Nascosto'),
        ),
    ]
