# Generated by Django 5.0.14 on 2025-09-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_add_recurring_and_hidden_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedexpense',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensile'), ('bimonthly', 'Bimestrale'), ('quarterly', 'Trimestrale')], default='monthly', max_length=20, null=True, verbose_name='Frequenza ricorrenza'),
        ),
    ]
