# Generated by Django 5.0.14 on 2025-09-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_add_quarterly_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedexpense',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Nascondi questa spesa dalla visualizzazione (utile per spese già pagate)', verbose_name='Nascosta'),
        ),
    ]
