# Generated by Django 5.0.14 on 2025-09-28 10:39

from django.db import migrations, models


def migrate_is_shared_to_plan_scope(apps, schema_editor):
    """Migra i dati da is_shared a plan_scope"""
    SpendingPlan = apps.get_model('reports', 'SpendingPlan')

    for plan in SpendingPlan.objects.all():
        # Se is_shared è True -> family, se False -> personal
        if plan.is_shared:
            plan.plan_scope = 'family'
        else:
            plan.plan_scope = 'personal'
        plan.save(update_fields=['plan_scope'])


def reverse_migrate_plan_scope_to_is_shared(apps, schema_editor):
    """Operazione inversa per rollback"""
    SpendingPlan = apps.get_model('reports', 'SpendingPlan')

    for plan in SpendingPlan.objects.all():
        # Se plan_scope è family -> True, se personal -> False
        plan.is_shared = (plan.plan_scope == 'family')
        plan.save(update_fields=['is_shared'])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_add_is_hidden_to_planned_expense'),
    ]

    operations = [
        # 1. Aggiungi il nuovo campo plan_scope
        migrations.AddField(
            model_name='spendingplan',
            name='plan_scope',
            field=models.CharField(
                choices=[('family', 'Piano Familiare'), ('personal', 'Piano Personale')],
                default='family',
                help_text='Familiare: condiviso con tutti i membri famiglia. Personale: visibile solo al creatore',
                max_length=10,
                verbose_name='Ambito piano'
            ),
        ),
        # 2. Migra i dati esistenti
        migrations.RunPython(
            migrate_is_shared_to_plan_scope,
            reverse_migrate_plan_scope_to_is_shared
        ),
        # 3. Rimuovi il campo is_shared obsoleto
        migrations.RemoveField(
            model_name='spendingplan',
            name='is_shared',
        ),
    ]
