# Generated by Django 5.0.14 on 2025-09-30 21:27

from django.db import migrations


def fix_priority_values(apps, schema_editor):
    """Convert numeric priority values to string choices"""
    PlannedExpense = apps.get_model('reports', 'PlannedExpense')

    # Mapping da numeri a valori corretti
    priority_map = {
        '1': 'low',
        '2': 'medium',
        '3': 'high',
        '4': 'urgent'
    }

    # Trova e fixa tutte le priorità numeriche
    for expense in PlannedExpense.objects.all():
        if expense.priority in priority_map:
            expense.priority = priority_map[expense.priority]
            expense.save(update_fields=['priority'])


def reverse_fix(apps, schema_editor):
    """Reverse migration (optional)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_add_plan_scope_field'),
    ]

    operations = [
        migrations.RunPython(fix_priority_values, reverse_fix),
    ]
