# Generated by Django 5.0.14 on 2025-10-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_fix_priority_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingplan',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Se True, il piano viene mostrato in cima e in evidenza', verbose_name='Pinnati'),
        ),
    ]
