# Generated by Django 5.0.14 on 2025-10-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_spendingplan_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spendingplan',
            options={'ordering': ['-is_pinned', '-start_date', '-created_at'], 'verbose_name': 'Piano Spese', 'verbose_name_plural': 'Piani Spese'},
        ),
    ]
