# Generated by Django 5.2.7 on 2025-10-02 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategory_icon'),
        ('expenses', '0006_expense_payment_source_alter_expense_payment_method_and_more'),
        ('reports', '0013_alter_spendingplan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plannedexpense',
            index=models.Index(fields=['spending_plan', 'is_completed'], name='planned_exp_plan_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedexpense',
            index=models.Index(fields=['parent_recurring_id', 'installment_number'], name='planned_exp_recurring_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedexpense',
            index=models.Index(fields=['due_date', '-priority'], name='planned_exp_due_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedexpense',
            index=models.Index(fields=['is_hidden', 'due_date'], name='planned_exp_hidden_idx'),
        ),
        migrations.AddIndex(
            model_name='spendingplan',
            index=models.Index(fields=['-start_date', '-created_at'], name='spending_plan_date_idx'),
        ),
        migrations.AddIndex(
            model_name='spendingplan',
            index=models.Index(fields=['plan_scope', 'is_active'], name='spending_plan_scope_active_idx'),
        ),
        migrations.AddIndex(
            model_name='spendingplan',
            index=models.Index(fields=['-is_pinned', '-start_date'], name='spending_plan_pinned_idx'),
        ),
        migrations.AddIndex(
            model_name='spendingplan',
            index=models.Index(fields=['is_hidden', '-start_date'], name='spending_plan_hidden_idx'),
        ),
    ]
