# Generated by Django 5.2.7 on 2025-10-02 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpendingPlanPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False, help_text='Se True, il piano appare in cima alla lista per questo utente', verbose_name='Pinnato')),
                ('custom_order', models.IntegerField(blank=True, help_text="Permette all'utente di riordinare manualmente i piani", null=True, verbose_name='Ordinamento personalizzato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spending_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='reports.spendingplan', verbose_name='Piano di spesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_plan_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Preferenza Piano Spese',
                'verbose_name_plural': 'Preferenze Piani Spese',
                'indexes': [models.Index(fields=['user', 'is_pinned'], name='user_pref_user_pinned_idx')],
                'unique_together': {('user', 'spending_plan')},
            },
        ),
    ]
