# Generated by Django 5.0.14 on 2025-10-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_add_user_spending_plan_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedexpense',
            name='my_share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importo effettivamente pagato da me (solo per spese parziali)', max_digits=10, null=True, verbose_name='Mia Quota'),
        ),
        migrations.AddField(
            model_name='plannedexpense',
            name='payment_type',
            field=models.CharField(choices=[('shared', 'Condivisa'), ('partial', 'Parziale'), ('individual', 'Individuale')], default='shared', help_text='Indica se la spesa è condivisa, parziale o individuale', max_length=20, verbose_name='Tipo Pagamento'),
        ),
    ]
