# Generated by Django 5.0.14 on 2025-10-02 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_plannedexpense_my_share_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedexpense',
            name='paid_by_user',
            field=models.ForeignKey(blank=True, help_text='Utente che paga la spesa (solo per spese individuali)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_planned_expenses_paid', to=settings.AUTH_USER_MODEL, verbose_name='Pagata da'),
        ),
    ]
