# Generated by Django 5.1.7 on 2025-09-16 22:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Es: 'Budget Gennaio 2024' o 'Vacanze Sicilia 2024'", max_length=255, verbose_name='Nome Budget')),
                ('description', models.TextField(blank=True, help_text='Dettagli aggiuntivi sul budget', verbose_name='Descrizione')),
                ('budget_type', models.CharField(choices=[('mensile', 'Budget Mensile'), ('evento', 'Evento Specifico')], default='mensile', max_length=20, verbose_name='Tipo Budget')),
                ('event_type', models.CharField(blank=True, choices=[('vacanze', 'Vacanze'), ('matrimonio', 'Matrimonio'), ('ristrutturazione', 'Ristrutturazione'), ('auto', 'Acquisto Auto'), ('casa', 'Acquisto Casa'), ('compleanno', 'Festa Compleanno'), ('natale', 'Regali Natale'), ('scuola', 'Spese Scolastiche'), ('medico', 'Spese Mediche'), ('altro', 'Altro Evento')], help_text="Solo se tipo budget è 'evento'", max_length=20, null=True, verbose_name='Tipo Evento')),
                ('year', models.IntegerField(blank=True, help_text='Per budget mensili', null=True, verbose_name='Anno')),
                ('month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Per budget mensili', null=True, verbose_name='Mese')),
                ('start_date', models.DateField(blank=True, help_text='Per eventi specifici', null=True, verbose_name='Data Inizio')),
                ('end_date', models.DateField(blank=True, help_text='Per eventi specifici', null=True, verbose_name='Data Fine')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Budget Totale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budget',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('notes', models.TextField(blank=True, verbose_name='Note aggiuntive')),
                ('date', models.DateField(verbose_name='Data della spesa')),
                ('payment_method', models.CharField(choices=[('contanti', 'Contanti'), ('carta_credito', 'Carta di Credito'), ('carta_debito', 'Carta di Debito'), ('bonifico', 'Bonifico'), ('assegno', 'Assegno'), ('paypal', 'PayPal'), ('altro', 'Altro')], default='contanti', max_length=20, verbose_name='Metodo di pagamento')),
                ('status', models.CharField(choices=[('pianificata', 'Pianificata'), ('da_pagare', 'Da Pagare'), ('parzialmente_pagata', 'Parzialmente Pagata'), ('pagata', 'Pagata'), ('ricorrente', 'Ricorrente'), ('annullata', 'Annullata')], default='pagata', max_length=20, verbose_name='Stato')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Ricevuta/Scontrino')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Spesa ricorrente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spesa',
                'verbose_name_plural': 'Spese',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expense_attachments/%Y/%m/', verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrizione')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Allegato Spesa',
                'verbose_name_plural': 'Allegati Spese',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_number', models.PositiveIntegerField(help_text='Numero progressivo della quota (1, 2, 3...)', verbose_name='Numero quota')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo quota')),
                ('due_date', models.DateField(help_text='Data entro cui deve essere pagata questa quota', verbose_name='Data scadenza')),
                ('paid_date', models.DateField(blank=True, help_text='Data in cui è stata effettivamente pagata', null=True, verbose_name='Data pagamento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagata')),
                ('payment_method', models.CharField(blank=True, choices=[('contanti', 'Contanti'), ('carta_credito', 'Carta di Credito'), ('carta_debito', 'Carta di Debito'), ('bonifico', 'Bonifico'), ('assegno', 'Assegno'), ('paypal', 'PayPal'), ('altro', 'Altro')], help_text='Metodo usato per pagare questa quota specifica', max_length=20, null=True, verbose_name='Metodo di pagamento')),
                ('notes', models.TextField(blank=True, help_text='Note specifiche per questa quota', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quota Spesa',
                'verbose_name_plural': 'Quote Spese',
                'ordering': ['expense', 'quota_number'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('frequency', models.CharField(choices=[('giornaliera', 'Giornaliera'), ('settimanale', 'Settimanale'), ('bisettimanale', 'Bisettimanale'), ('mensile', 'Mensile'), ('bimestrale', 'Bimestrale'), ('trimestrale', 'Trimestrale'), ('semestrale', 'Semestrale'), ('annuale', 'Annuale')], default='mensile', max_length=20, verbose_name='Frequenza')),
                ('start_date', models.DateField(verbose_name='Data di inizio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data di fine')),
                ('payment_method', models.CharField(choices=[('contanti', 'Contanti'), ('carta_credito', 'Carta di Credito'), ('carta_debito', 'Carta di Debito'), ('bonifico', 'Bonifico'), ('assegno', 'Assegno'), ('paypal', 'PayPal'), ('altro', 'Altro')], default='bonifico', max_length=20, verbose_name='Metodo di pagamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('last_generated', models.DateField(blank=True, null=True, verbose_name='Ultima generazione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spesa Ricorrente',
                'verbose_name_plural': 'Spese Ricorrenti',
                'ordering': ['frequency', 'description'],
            },
        ),
    ]
