# Generated by Django 5.1.7 on 2025-09-16 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Creato da'),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(blank=True, help_text='Budget mensile o evento a cui appartiene questa spesa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_expenses', to='expenses.budget', verbose_name='Budget di appartenenza'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='expense',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Condivisa con'),
        ),
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='categories.subcategory', verbose_name='Sottocategoria'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AddField(
            model_name='expenseattachment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expenses.expense', verbose_name='Spesa'),
        ),
        migrations.AddField(
            model_name='expensequota',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='expenses.expense', verbose_name='Spesa'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_recurring_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Condivisa con'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory', verbose_name='Sottocategoria'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('budget_type', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='expenses_ex_date_2850f8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-date'], name='expenses_ex_user_id_4af51e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', '-date'], name='expenses_ex_categor_bb2d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='expensequota',
            index=models.Index(fields=['expense', 'quota_number'], name='expenses_ex_expense_7b61ab_idx'),
        ),
        migrations.AddIndex(
            model_name='expensequota',
            index=models.Index(fields=['due_date'], name='expenses_ex_due_dat_10a6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='expensequota',
            index=models.Index(fields=['is_paid'], name='expenses_ex_is_paid_88110d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensequota',
            unique_together={('expense', 'quota_number')},
        ),
    ]
