# Generated by Django 5.1.7 on 2025-09-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
        ('reports', '0004_create_spending_plan_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='planned_expense',
            field=models.ForeignKey(blank=True, help_text='Spesa pianificata a cui questo pagamento contribuisce', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_payments', to='reports.plannedexpense', verbose_name='Spesa Pianificata'),
        ),
    ]
