# Generated by Django 5.0.14 on 2025-09-17 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_planned_expense'),
        ('reports', '0004_create_spending_plan_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='spending_plan',
            field=models.ForeignKey(blank=True, help_text='Piano di spesa a cui appartiene questa spesa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_expenses', to='reports.spendingplan', verbose_name='Piano di Spesa'),
        ),
    ]
