# Generated by Django 5.1.7 on 2025-09-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_spending_plan'),
    ]

    operations = [
        # Indici per performance su tabella expenses_expense
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_expense_date_user ON expenses_expense (date, user_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_expense_date_user;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_expense_category ON expenses_expense (category_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_expense_category;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_expense_status ON expenses_expense (status);",
            reverse_sql="DROP INDEX IF EXISTS idx_expense_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_expense_user_date ON expenses_expense (user_id, date DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_expense_user_date;"
        ),

        # Indici per performance su tabelle correlate
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_quota_due_date ON expenses_expensequota (due_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_quota_due_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_quota_expense_status ON expenses_expensequota (expense_id, is_paid);",
            reverse_sql="DROP INDEX IF EXISTS idx_quota_expense_status;"
        ),
    ]
