# Generated by Django 5.0.14 on 2025-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0005_auto_20250926_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_source",
            field=models.CharField(
                choices=[
                    ("personal", "Fondi Personali"),
                    ("contribution", "Da Contributo Famiglia"),
                ],
                default="personal",
                help_text="Indica se il pagamento viene da fondi personali o dal contributo famiglia",
                max_length=20,
                verbose_name="Fonte del Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("contanti", "Contanti"),
                    ("carta_credito", "Carta di Credito"),
                    ("carta_debito", "Carta di Debito"),
                    ("bonifico", "Bonifico"),
                    ("assegno", "Assegno"),
                    ("paypal", "PayPal"),
                    ("contributo", "Da Contributo Famiglia"),
                    ("altro", "Altro"),
                ],
                default="contanti",
                max_length=20,
                verbose_name="Metodo di pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="expensequota",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contanti", "Contanti"),
                    ("carta_credito", "Carta di Credito"),
                    ("carta_debito", "Carta di Debito"),
                    ("bonifico", "Bonifico"),
                    ("assegno", "Assegno"),
                    ("paypal", "PayPal"),
                    ("contributo", "Da Contributo Famiglia"),
                    ("altro", "Altro"),
                ],
                help_text="Metodo usato per pagare questa quota specifica",
                max_length=20,
                null=True,
                verbose_name="Metodo di pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="recurringexpense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("contanti", "Contanti"),
                    ("carta_credito", "Carta di Credito"),
                    ("carta_debito", "Carta di Debito"),
                    ("bonifico", "Bonifico"),
                    ("assegno", "Assegno"),
                    ("paypal", "PayPal"),
                    ("contributo", "Da Contributo Famiglia"),
                    ("altro", "Altro"),
                ],
                default="bonifico",
                max_length=20,
                verbose_name="Metodo di pagamento",
            ),
        ),
    ]
